"""baseline schema

Revision ID: 4cf63d43cd4c
Revises: 
Create Date: 2026-07-12 06:36:16.904534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cf63d43cd4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forwarded', sa.Boolean(), nullable=False),
    sa.Column('issue_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_logo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('formation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_duration_mins', sa.Integer(), nullable=False),
    sa.Column('has_halftime', sa.Integer(), nullable=False),
    sa.Column('fairness_value', sa.Integer(), nullable=False),
    sa.Column('rotation_intensity', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_position_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quarters', sa.Integer(), nullable=False),
    sa.Column('quarter_length_mins', sa.Integer(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('formation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fairness', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fairness_value', sa.Integer(), nullable=False),
    sa.Column('rotation_intensity', sa.Integer(), nullable=False),
    sa.Column('home_away', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opponent_goals', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_slot', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('tournament_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gk_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('def_restricted', sa.Boolean(), nullable=False),
    sa.Column('skill_rating', sa.Integer(), nullable=False),
    sa.Column('preferred_positions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('best_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('source_tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('slots_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warnings_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goals_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('available_player_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('removed_players_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotation_plans')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('squads')
    op.drop_table('feedback')
    # ### end Alembic commands ###
